### ISSUE TITLE
Does Searchonymous2 work with FF 53.0.3 (64-bit) ?

### ISSUE THREAD

**Issue by gitgetgot** [DaAwesomeP/Searchonymous2#2]
Hi,
I recently switched from Searchonymous to Searchonymous2.
Unfortunately, Searchonymous2 does not work properly.

So I give a little info about my setting (Win7, FF 53.0.3) and want to ask, if it might be the "old" version of FF, why its "not working".

"not working":
I start FF, open a YT page and log in with my google account.
I use the searchbar (with google as the default search engine) to type "test" and a new tab opens, showing search results AND my (logged in via another tab) google account.

Afair, in older versions of Searchonymous the tab with the search results never showed my credentials from another yt-tab.

Maybe I don't recall correctly....

Any Help anyone? 

(and thanks to the developer(s) for forking and helping the community which likes to stay somewhat anonymous!!)

**Comment by DaAwesomeP** [comment]
Hi @gitgetgot, thank you for reporting this issue. Unfortunately, I cannot replicate your issue. Please ensure that the old version of Searchonymous is disabled before installing Searchonymous2. Also, **your version of Firefox is several months old (April 2017) and is most likely a security risk.** I faintly recall some issues with WebExtensions some time ago. Please update to Firefox 57 (latest as of 12/11/2017) and enable automatic updates and try the addon again.

**Comment by gitgetgot** [comment]
Thank you. Searchonymous is removed and shouldnt bother.
Updating FF is no option, so I guess, I'm stuck here. Thanks anyways.
